### ISSUE TITLE
support for python 3.8

### ISSUE THREAD

**Issue by commonism** [Colin-b/pytest_httpx#122] opened 2023-10-27 08:58 UTC
Hi,

support for python 3.8 was dropped in https://github.com/Colin-b/pytest_httpx/commit/d6a58906015ef76e5e86c101b8f65851b237f409 released in [0.23 ](https://github.com/Colin-b/pytest_httpx/releases/tag/v0.23.0)

When using dependency tracking software such as pdm, this requires projects using pytest_httpx to require python 3.9 as well or stick with httpx 0.24.1 due to the python version requirement and httpx version dependency of pytest_httpx. Even when using python 3.10.

I'd appreciate if 3.8 could be re-added to the list to allow using httpx >=0.24.1 in projects supporting python 3.8.
It would be [11 more months until 3.8 is eol](https://endoflife.date/python).

**Comment by nicolewhite** [comment] 2023-10-31 02:40
+1 please add back 3.8, this means packages that still want to support 3.8 for their end users can no longer use pytest-httpx

**Comment by Colin-b** [comment] 2023-11-09 18:06
Hello, this is a duplicate of #109

**Closed by Colin-b** 2023-11-09 18:06 UTC
Labels: duplicate
